# ---------------------------------------------------------------------------
# AI Explain layer — mirrors ai-orchestration.ts principle:
#   This module ONLY explains model outputs. It never computes, invents, or
#   adjusts numeric values. All numbers arrive from deterministic ML models.
# ---------------------------------------------------------------------------

from __future__ import annotations

import os
import logging

logger = logging.getLogger(__name__)

DISCLAIMER = (
    "This explanation is generated by the AI layer. "
    "All numeric values (yield, risk scores, factor weights, percentiles) "
    "are computed by deterministic ML models trained on historical data — "
    "not estimated or invented by AI."
)


# ---------------------------------------------------------------------------
# LLM stub — real OpenAI/Gemini call drops in here.
# MUST NEVER alter or fabricate numeric values.
# ---------------------------------------------------------------------------

async def _call_llm_stub(prompt: str) -> str | None:
    api_key = os.environ.get("OPENAI_API_KEY") or os.environ.get("GEMINI_API_KEY")
    if not api_key:
        return None
    # Future: call OpenAI/Gemini with prompt that includes the pre-computed
    # numbers and asks only for plain-English narrative.
    return None


# ---------------------------------------------------------------------------
# Explanation templates (used when LLM returns None)
# ---------------------------------------------------------------------------

def explain_yield(
    predicted_kg_ha: float,
    baseline_kg_ha: float,
    confidence: str,
    limiting_factors: list[str],
    factor_water: float,
    factor_nutrient: float,
    crop_name: str,
) -> str:
    delta = predicted_kg_ha - baseline_kg_ha
    direction = "above" if delta >= 0 else "below"
    pct = abs(delta / (baseline_kg_ha + 1e-9)) * 100

    limits = " and ".join(f.replace("_", " ") for f in limiting_factors[:2]) or "unknown"

    return (
        f"The model predicts {predicted_kg_ha:,.0f} kg/ha for {crop_name} — "
        f"{pct:.1f}% {direction} the {baseline_kg_ha:,.0f} kg/ha historical baseline. "
        f"The top limiting factors are {limits}. "
        f"Water accounts for {factor_water*100:.0f}% and nutrients {factor_nutrient*100:.0f}% "
        f"of the prediction's sensitivity. "
        f"Confidence is {confidence} based on available historical records."
    )


def explain_optimization(
    current_irrigation_in: float,
    rec_irrigation_in: float,
    current_n: float,
    rec_n: float,
    expected_gain_pct: float,
    confidence: str,
) -> str:
    irr_delta = rec_irrigation_in - current_irrigation_in
    n_delta = rec_n - current_n

    irr_msg = (
        f"increase irrigation by {irr_delta:.1f} in" if irr_delta > 0.5
        else f"reduce irrigation by {abs(irr_delta):.1f} in" if irr_delta < -0.5
        else "maintain current irrigation"
    )
    n_msg = (
        f"apply {n_delta:.0f} lb/ac more nitrogen" if n_delta > 5
        else f"reduce nitrogen by {abs(n_delta):.0f} lb/ac" if n_delta < -5
        else "maintain current nitrogen programme"
    )

    return (
        f"The optimizer recommends to {irr_msg} and {n_msg}. "
        f"This is projected to improve yield by {expected_gain_pct:.1f}% (confidence: {confidence}). "
        f"Recommendations are derived from partial-dependence analysis over the trained yield model; "
        f"all projections are model estimates and should be validated against local conditions."
    )


def explain_risk(
    risk_label: str,
    anomaly_score: float,
    top_risk_factors: list[str],
    residual_zscore: float,
) -> str:
    factors = ", ".join(f.replace("_", " ") for f in top_risk_factors[:3]) or "unknown"
    return (
        f"Risk assessment: {risk_label} (anomaly score {anomaly_score:.2f}). "
        f"This field deviates {residual_zscore:.1f} standard deviations from its peer cohort on: {factors}. "
        f"The Isolation Forest algorithm flagged these deviations based on patterns in the training dataset. "
        f"This is a statistical signal — agronomic context should always inform the final decision."
    )


def explain_benchmark(
    percentile_rank: float,
    cohort_size: int,
    cluster_name: str,
    yield_kg_ha: float,
) -> str:
    return (
        f"This field ranks at the {percentile_rank:.0f}th percentile within its peer group: "
        f"\"{cluster_name}\" ({cohort_size} comparable fields). "
        f"Predicted yield of {yield_kg_ha:,.0f} kg/ha places it "
        f"{'above' if percentile_rank >= 50 else 'below'} the cohort median. "
        f"Percentile ranking is based on k-means cohort assignment using "
        f"agronomic input features and field characteristics."
    )


async def build_yield_explanation(result: dict) -> dict:
    prompt = (
        f"Explain in 2-3 plain-English sentences why the yield model predicted "
        f"{result['predicted_yield_kg_ha']:.0f} kg/ha for {result.get('crop_name','this crop')}. "
        f"Limiting factors: {result.get('limiting_factors',[])}. "
        f"Do not change any numbers."
    )
    llm_text = await _call_llm_stub(prompt)
    text = llm_text or explain_yield(
        predicted_kg_ha=result["predicted_yield_kg_ha"],
        baseline_kg_ha=result.get("baseline_yield_kg_ha", result["predicted_yield_kg_ha"]),
        confidence=result.get("confidence", "medium"),
        limiting_factors=result.get("limiting_factors", []),
        factor_water=result.get("factor_water", 0.3),
        factor_nutrient=result.get("factor_nutrient", 0.3),
        crop_name=result.get("crop_name", "crop"),
    )
    return {"explanation": text, "disclaimer": DISCLAIMER}
