// ---------------------------------------------------------------------------
// ML service types and mock data shared between ml-api.ts and tests.
//
// Architecture: all numbers here are deterministic (model outputs or mock
// constants). The AI explain layer in the Python service narrates them.
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// Canonical types (mirrors Python Pydantic models)
// ---------------------------------------------------------------------------

export interface YieldPrediction {
  field_id: string;
  crop_name: string;
  crop_year: number;
  predicted_yield_kg_ha: number;
  yield_lower_kg_ha: number;
  yield_upper_kg_ha: number;
  baseline_yield_kg_ha: number;
  confidence: 'low' | 'medium' | 'high';
  factor_water: number;
  factor_nutrient: number;
  factor_heat: number;
  factor_uv: number;
  factor_seed: number;
  factor_planting: number;
  limiting_factors: string[];
  explanation: string;
  disclaimer: string;
}

export interface OptimizationResult {
  field_id: string;
  crop_year: number;
  current_irrigation_in: number;
  rec_irrigation_in: number;
  irrigation_delta_in: number;
  current_nitrogen_lb_ac: number;
  rec_nitrogen_lb_ac: number;
  nitrogen_delta_lb_ac: number;
  expected_yield_kg_ha: number;
  expected_yield_gain_pct: number;
  baseline_yield_kg_ha: number;
  confidence: 'low' | 'medium' | 'high';
  explanation: string;
  disclaimer: string;
}

export interface RiskAssessment {
  field_id: string;
  crop_year: number;
  anomaly_score: number;
  risk_label: 'low' | 'moderate' | 'high' | 'critical';
  residual_zscore: number;
  top_risk_factors: string[];
  cohort_id: number;
  cohort_name: string;
  explanation: string;
  disclaimer: string;
}

export interface RiskSummary {
  crop_year: number;
  fields: RiskAssessment[];
}

export interface BenchmarkResult {
  field_id: string;
  crop_year: number;
  cluster_label: number;
  cluster_name: string;
  yield_kg_ha: number;
  percentile_rank: number;
  cohort_size: number;
  explanation: string;
  disclaimer: string;
}

export interface ClusterInfo {
  cluster_label: number;
  cluster_name: string;
}

export interface MlHealthStatus {
  status: 'ok' | 'degraded';
  demo_mode: boolean;
  active_models: Record<string, string | null>;
}

// ---------------------------------------------------------------------------
// Mock builders — deterministic, never invented by AI
// ---------------------------------------------------------------------------

const DISCLAIMER =
  'This explanation is generated by the AI layer. ' +
  'All numeric values are computed by deterministic ML models trained on historical data — ' +
  'not estimated or invented by AI.';

const CROP_BASELINES: Record<string, number> = {
  almond: 4100,
  tomato: 84000,
  pistachio: 2950,
  grape: 14000,
  alfalfa: 18000,
};

export function MOCK_YIELD(fieldId: string, cropName: string): YieldPrediction {
  const baseline = CROP_BASELINES[cropName.toLowerCase()] ?? 4100;
  const predicted = Math.round(baseline * (0.92 + (hashCode(fieldId) % 100) / 500));
  const interval = Math.round(predicted * 0.12);
  const water = 0.38;
  const nutrient = 0.29;

  return {
    field_id: fieldId,
    crop_name: cropName,
    crop_year: 2026,
    predicted_yield_kg_ha: predicted,
    yield_lower_kg_ha: predicted - interval,
    yield_upper_kg_ha: predicted + interval,
    baseline_yield_kg_ha: baseline,
    confidence: 'high',
    factor_water: water,
    factor_nutrient: nutrient,
    factor_heat: 0.15,
    factor_uv: 0.08,
    factor_seed: 0.06,
    factor_planting: 0.04,
    limiting_factors: ['water', 'nutrient'],
    explanation:
      `The model predicts ${predicted.toLocaleString()} kg/ha for ${cropName} — ` +
      `${((predicted - baseline) / baseline * 100).toFixed(1)}% ` +
      `${predicted >= baseline ? 'above' : 'below'} the ${baseline.toLocaleString()} kg/ha historical baseline. ` +
      `Water accounts for ${Math.round(water * 100)}% and nutrients ${Math.round(nutrient * 100)}% of sensitivity. ` +
      `Confidence is high based on available historical records.`,
    disclaimer: DISCLAIMER,
  };
}

export function MOCK_OPTIMIZE(fieldId: string): OptimizationResult {
  return {
    field_id: fieldId,
    crop_year: 2026,
    current_irrigation_in: 42.0,
    rec_irrigation_in: 46.5,
    irrigation_delta_in: 4.5,
    current_nitrogen_lb_ac: 180.0,
    rec_nitrogen_lb_ac: 210.0,
    nitrogen_delta_lb_ac: 30.0,
    expected_yield_kg_ha: 4380,
    expected_yield_gain_pct: 6.3,
    baseline_yield_kg_ha: 4120,
    confidence: 'medium',
    explanation:
      'The optimizer recommends to increase irrigation by 4.5 in and apply 30 lb/ac more nitrogen. ' +
      'This is projected to improve yield by 6.3% (confidence: medium). ' +
      'Recommendations are derived from partial-dependence analysis over the trained yield model.',
    disclaimer: DISCLAIMER,
  };
}

export function MOCK_RISK_SUMMARY(): RiskAssessment[] {
  return [
    {
      field_id: 'field-001',
      crop_year: 2026,
      anomaly_score: 0.68,
      risk_label: 'high',
      residual_zscore: 2.1,
      top_risk_factors: ['season_irrigation_in', 'soil_ph', 'organic_matter_pct'],
      cohort_id: 0,
      cohort_name: 'High-input intensive',
      explanation:
        'Risk assessment: high (anomaly score 0.68). This field deviates 2.1 standard deviations ' +
        'from its peer cohort on: season irrigation, soil pH, organic matter. ' +
        'The Isolation Forest algorithm flagged these deviations based on patterns in the training dataset.',
      disclaimer: DISCLAIMER,
    },
    {
      field_id: 'field-002',
      crop_year: 2026,
      anomaly_score: 0.31,
      risk_label: 'low',
      residual_zscore: 0.8,
      top_risk_factors: ['nitrate_n_ppm', 'phosphorus_ppm'],
      cohort_id: 1,
      cohort_name: 'Mixed cohort 1',
      explanation:
        'Risk assessment: low (anomaly score 0.31). This field is within normal range of its peer cohort.',
      disclaimer: DISCLAIMER,
    },
    {
      field_id: 'field-003',
      crop_year: 2026,
      anomaly_score: 0.44,
      risk_label: 'moderate',
      residual_zscore: 1.3,
      top_risk_factors: ['potassium_ppm', 'season_n_applied'],
      cohort_id: 2,
      cohort_name: 'Low-input conservative',
      explanation:
        'Risk assessment: moderate (anomaly score 0.44). Nutrient levels deviate moderately from cohort median.',
      disclaimer: DISCLAIMER,
    },
  ];
}

export function MOCK_BENCHMARK(fieldId: string): BenchmarkResult {
  const pct = 55 + (hashCode(fieldId) % 30);
  return {
    field_id: fieldId,
    crop_year: 2026,
    cluster_label: 0,
    cluster_name: 'High-input intensive',
    yield_kg_ha: 4380,
    percentile_rank: pct,
    cohort_size: 47,
    explanation:
      `This field ranks at the ${pct}th percentile within its peer group: ` +
      `"High-input intensive" (47 comparable fields). ` +
      `Percentile ranking is based on k-means cohort assignment using agronomic input features.`,
    disclaimer: DISCLAIMER,
  };
}

export const MOCK_CLUSTERS: ClusterInfo[] = [
  { cluster_label: 0, cluster_name: 'High-input intensive' },
  { cluster_label: 1, cluster_name: 'Mixed cohort 1' },
  { cluster_label: 2, cluster_name: 'Low-input conservative' },
  { cluster_label: 3, cluster_name: 'Irrigation-intensive' },
  { cluster_label: 4, cluster_name: 'Nutrient-intensive' },
  { cluster_label: 5, cluster_name: 'Mixed cohort 5' },
];

function hashCode(s: string): number {
  let h = 0;
  for (let i = 0; i < s.length; i++) {
    h = (Math.imul(31, h) + s.charCodeAt(i)) >>> 0;
  }
  return h;
}
